### ISSUE TITLE
Use an open protocol for messaging

### ISSUE THREAD

**Issue by john-light** [cryptocat/cryptocat#101]
The crypto.cat server is currently a central point of failure. Swap out the underlying centralized message transport protocol for an open protocol that anyone can set up a server for e.g. XMPP or Matrix.

**Comment by kaepora** [comment]
Cryptocat uses XMPP. Please do not open issues without first doing your homework. Repeat offenders will be blocked from opening new issues.

**Comment by john-light** [comment]
At first I did a ctrl+F search of your top-level documentation on crypto.cat and here on GitHub and found nothing about XMPP or the message transport protocol in general, so assumed it used a centralized architecture, nothing special. After your reply here I did a search in your repo and see that it does use XMPP. Apologies for the oversight on my part.

I would now amend this issue or open a new issue like "Create documention for how the user can set up their own cryptocat XMPP server and use it to talk to other cryptocat users or other xmpp clients that implement the same encryption protocol." Would this be a reasonable request? If so, do you prefer a new issue or to edit this one and re-open it?

**Comment by DreamFlasher** [comment]
@kaepora I'd appreciate an answer to @john-light question, too. How is it possible to connect with for example Conversations users?
