### ISSUE TITLE
Use blockchain ID PKI

### ISSUE THREAD

**Issue by john-light** [cryptocat/cryptocat#102]
Right now key verification must be done out-of-band. If you bind public keys to a blockchain ID then users only need to know their counterparty's blockchain ID in order to get the correct keypair, no out-of-band verification required (unless the blockchain ID itself must be verified, but this is much easier than reading a long key fingerprint). In this scenario, the blockchain ID can be the username as well. See blockstack.org/docs for documentation and https://github.com/blockstack for code.

**Comment by kaepora** [comment]
Certificate transparency will be implemented in the future, but not in this style. However, I appreciate the general goal and thank you for your suggestion.

**Comment by john-light** [comment]
I would have to see your exact implementation of CT to understand if it is sufficient or if it accomplishes the same usability goal as blockchain DNS+PKI in this context, but if it is similar at all to the "official" Certificate Transparency spec as discussed [here](https://blog.okturtles.com/tag/certificate-transparency/) then I will have to say in advance that it is insufficient and does not go as far as blockchain DNS+PKI to ease usability and prevent man-in-the-middle attacks. As I understand it, CT is great for detecting MITM attacks after the fact, but powerless to prevent them. I am open to being corrected on this point.

A relevant quote from one of the posts linked above:

> It’s more meaningful to [prevent](https://blog.okturtles.com/2015/03/certificate-transparency-on-blockchains/) the attacks in the first place, but reliable detection of MITM attacks [via Certificate Transparency] is a real improvement over the web we have today.

https://blog.okturtles.com/2015/03/certificate-transparencys-improved-gossip-protocols-show-promise/

To clarify, the purpose of blockchain DNS+PKI as described in this issue is to:

1. Provide a decentralized username system with portable IDs.
2. Bind public keys to usernames without a central authority or trusted third party.
3. Eliminate the need to verify public key fingerprints out-of-band, instead using the blockchain ID to verifiably retrieve the correct public key.

Again, I'd have to see the details of the CT spec you are implementing but if it is like the CT spec described in the links above then it does not accomplish the same purpose as blockchain DNS+PKI.
