### ISSUE TITLE
Offline messages can't be decrypted.

### ISSUE THREAD

**Issue by ledti** [cryptocat/cryptocat#103]
Most of the time (95%~) when I send offline messages to a friend, or vice-versa, instead of either of us getting the messages we just get a warning that they couldn't be decrypted. This happens for each and every message, of which there can sometimes be 10 or more.

There's a 1~ second pause before receiving each warning.

It might be worth noting that I generally use the Linux binaries, while he uses the Windows binaries.

**Comment by kaepora** [comment]
Cannot reproduce.
