### ISSUE TITLE
Markdown and Code Syntax Highlighting

### ISSUE THREAD

**Issue by armand1m** [cryptocat/cryptocat#104]
Sometimes I find myself needing to share code through a chat application (Skype, telegram, etc) but it is kinda messy to send and write code on those, since there is no auto tabbing or syntax highlighting. What if I submit a Pull Request with a functionality for sharing code through crypto.cat with syntax highlighting?

**Comment by kaepora** [comment]
Cryptocat does not accept pull requests, and this is not a feature I'm willing to implement, sorry. Just send your code through as a file.
