### ISSUE TITLE
Reduce the size of cryptocat

### ISSUE THREAD

**Issue by jvoisin** [cryptocat/cryptocat#105]
Currently, my cryptocat folder has an on-disk size of **104.6MiB**. This is more than a [complete linux distribution]( http://alpinelinux.org/downloads/ ), or a [movie]( https://peach.blender.org/download/ ).

Can you please consider reducing the size of your software?

**Comment by kaepora** [comment]
What a novel idea! How didn't I think of this before? Wow! Let me just pull out my magic wand and make the Electron runtime 50MB smaller for you.

> Can you please consider reducing the size of your software?

I'm banning you from opening further issues.
