### ISSUE TITLE
No auto scroll

### ISSUE THREAD

**Issue by CorbanR** [cryptocat/cryptocat#108]
I find if I'm catching up on reading messages, and the person is still sending me text(or pictures), the scroll bar keeps jumping to the most recent message.. It would be nice if I could finish reading the previous text. 

Also, Love crypto.cat so far :). Keep up the good work!

**Comment by kaepora** [comment]
Yes, auto-scroll should be disabled if you're scrolled up to read messages. Will implement.

**Comment by CorbanR** [comment]
So I updated to 3.1.22 and I still seemed to have the autoscroll problem. Will check in 3.1.23

**Comment by kaepora** [comment]
You're not scrolling up high enough.
