### ISSUE TITLE
Decentralization for Cryptocat

### ISSUE THREAD

**Issue by ovalseven8** [cryptocat/cryptocat#11]
As far as I understand the new Cryptocat software, it works with a single (?) XMPP server (please correct me if I am wrong, I couldn't finde more information).

So, if this server gets attacked or down for whatever reason, nobody will be able to communicate via Cryptocat. I think it makes sense to think about how to decentralize the Cryptocat infrastructure in a secure way so that you're able to register on different servers.

**Comment by kaepora** [comment]
This is not a priority at the moment.
