### ISSUE TITLE
Certificate pinning should not pin the fingerprint of the certificate itself

### ISSUE THREAD

**Issue by U3NoPo** [cryptocat/cryptocat#113]
Cryptocat's certificate pinning [checks the certificate fingerprint](https://github.com/cryptocat/cryptocat/blob/8b5b137cdbf1a93f51324c6689d913db3e0a5761/src/js/pinning.js#L5-L8) as well as a few other fields including the subject public key. It should not check the certificate fingerprint, or future reissued certificates with the same public key will be rejected. See https://www.imperialviolet.org/2011/05/04/pinning.html ("Why public key hashes, not certificate hashes?").

Compare to how pins are stored in Chromium ("These are SubjectPublicKeyInfo hashes for public key pinning").
https://chromium.googlesource.com/chromium/src.git/+/29e4ffb20aa905f8e00d7d22c189e9198fea9dac/net/http/transport_security_state_static.h#291

**Comment by kaepora** [comment]
Thanks, this is convincing and will be implemented.
