### ISSUE TITLE
adding a username that doesnt exist still gives the "user added" message and appears in buddy list

### ISSUE THREAD

**Issue by NIXOYE** [cryptocat/cryptocat#126]
this really sucks for when you mistype a buddies name and dont realize it but it says added so you think you spelt it correctly. Also, the fact that your required to go through a JS google captcha to sign up is in poor taste

**Comment by kaepora** [comment]
Implementing this would make username enumeration easier which raises privacy concerns.

**Comment by NIXOYE** [comment]
@kaepora enabling JS for some people is a privacy concern. couldn't it be replaced by a non-js captcha?
