### ISSUE TITLE
when clicking the close button i would like if it actually quit instead of going to tray

### ISSUE THREAD

**Issue by bugissue** [cryptocat/cryptocat#129]
i want the x to quit the application not just take it the drawer.

**Comment by kaepora** [comment]
Sorry, no. Cryptocat is meant to run in a style similar to Pidgin, which includes background-tray style desktop integration. There are many ways, however, that you can use to quickly quit Cryptocat:

* Press `Ctrl+Q` from the buddy list window.
* Right click the tray icon and select "*Quit*".
* In the buddy list window, click on the "*Account*" menu and then select "*Quit*".
