### ISSUE TITLE
Deterministic builds?

### ISSUE THREAD

**Issue by snap9** [cryptocat/cryptocat#130]
The Mission page https://crypto.cat/mission.html mentions "deterministic builds".
So, how do I actually confirm myself that the downloadable binaries on https://crypto.cat/index.html are coming from the source code they should be coming from?

**Comment by kaepora** [comment]
The deterministic build only applies to `app.asar`, the ASAR archive that contains Cryptocat. Since the claim on the website does not make the distinction between the ASAR archive and the Electron runtime itself (which is prebuilt), I'll be removing this claim from the website.

**Comment by snap9** [comment]
@kaepora 
Would there be no way to make the entire thing that a user downloads from crypto.cat deterministic?

**Comment by kaepora** [comment]
@snap9 There probably is a way, but I don't have the time to look into it right now.
