### ISSUE TITLE
Adding device popup really confuses first times users and isnt really useful.

### ISSUE THREAD

**Issue by bugissue** [cryptocat/cryptocat#132]
I don't really see the benfit to knowing what computer someone is using. if they are online thats all I care about. Also it just seems to open an attack vector knowing someone is on a mac or knowing nadim is using a thinkpad. Also everyone ive got on cryptocat seems to sign up and use it with no hiccup but they are always confused by that popup and dont understand why they even want it

**Comment by kaepora** [comment]
Please do not open tickets without even understanding the underlying issue you're discussing. Repeat offenses will lead to a ban.
