### ISSUE TITLE
icon request for numix circle theme for cryptocat

### ISSUE THREAD

**Issue by NIXOYE** [cryptocat/cryptocat#135]
would like to ask permission before i do just in case. 
https://github.com/numixproject/numix-icon-theme-circle is what im talking about.

To request an icon you need submit the current icon image and to go into /usr/share/applications and drag and drop the application into a text editor to get info like

```
/usr/share/applications » cat layout.desktop 
_[Desktop Entry]
Value=1.0
Type=Application
Name=LayoutEditor
GenericName=LayoutEditor for IC/MEMS design
Icon=layout.png
Exec=/usr/bin/layout %F
MimeType=application/gds;application/dxf;application/oasis;application/cif
Categories=Graphics;VectorGraphics;Science;Electronics;Electricity;Engineering_
```

for the icon name but cryptocat isnt placed there since its not installed like most applications so im wondering how i'd find that. what they need is the `icon= `name

**Comment by kaepora** [comment]
This issue board is for reporting bugs.
