### ISSUE TITLE
New PGP key

### ISSUE THREAD

**Issue by bungabunga** [cryptocat/cryptocat#137]
It seems that the latest CC release is signed with the different PGP key then the previous releases. Where can I get the new public key if i want to download and install Cryptocat manually?

Ubuntu 16.04.

**Comment by kaepora** [comment]
Indeed. I created a key that is compatible with older `gpg` versions so users would stop complaining.

The key is available [on the website](https://crypto.cat/help.html#signatures).

I have also recorded this video to help authenticate the key. It will be used for signing releases as well as signing GitHub code commits (the latter which I deem more important).

Here is [a video of me reading the new fingerprint](http://webmshare.com/BBNWW).
