### ISSUE TITLE
Self hosted server

### ISSUE THREAD

**Issue by Fastidious** [cryptocat/cryptocat#139]
Where can I find documentation on using Cryptocat with my own XMPP server? I am assuming the ones under the "legacy" wiki are just that, legacy. Thanks!

**Comment by kaepora** [comment]
Just set up your own XMPP server (I recommend Prosody or ejabberd) and fork Cryptocat, changing the server settings [here](https://github.com/cryptocat/cryptocat/blob/62c33db1a6f382a1c9ce548730ce9fa7b2244e5a/src/js/xmpp.js#L313-L328).

**Comment by beherit** [comment]
Yep, in that way we can change the server but still is not posibble to add buddy from other server ;_;

**Comment by tristan-k** [comment]
This would be a missing link, since setting up Gajim with Omemo is still difficult.

**Comment by Fastidious** [comment]
Coming back to this, could it be made configurable on the client itself? Any possibilities of that, @kaepora?

**Comment by nklose** [comment]
Is there a way to manually create accounts on a self-hosted server? When I try creating one through the interface it goes to http://[hostname]/create which times out (probably because I'm hosting a different server on port 80).

**Comment by Fastidious** [comment]
@nklose there is, but it varies depending on the self-hosted server you are using. It has nothing to do with Cryptocat though.
