### ISSUE TITLE
Offline buddies are sometimes red when they should be orange

### ISSUE THREAD

**Issue by ayyghost** [cryptocat/cryptocat#141]
Occasionally upon launching Cryptocat, buddies who should appear orange-offline (can receive messages) show up as red-offline (cannot receive messages). When I click each of their names, they become orange as expected, and I'm able to send offline messages to them.

It might be difficult to reproduce this issue since it doesn't happen all the time, but I assure you I'm not hallucinating. I've also spoken to others who have noticed this behavior.

**Comment by cataleap** [comment]
Yes. I experience the error as well, just on my Mac OS. I do not experience this with my Windows Account.
