### ISSUE TITLE
Unzip fallback

### ISSUE THREAD

**Issue by zpiman** [cryptocat/cryptocat#143]
I just want to point out that some distributions of Linux do not have the `zip` command installed by default. As a matter of convenience, it would be nice to provide a fallback to `unzip`, which I believe comes installed by default. The line in question is: https://github.com/cryptocat/cryptocat/blob/master/Gruntfile.js#L102

**Comment by kaepora** [comment]
Sorry, but adopting this workaround isn't justified.
