### ISSUE TITLE
x86 packages for Linux?

### ISSUE THREAD

**Issue by ghostlands** [cryptocat/cryptocat#149]
[x86_32]

It would be nice in general, but for some it would be essential. 3rd world and low budget compatibility is what is in mind here.

**Comment by kaepora** [comment]
Duplicate of #33.

**Comment by ghostlands** [comment]
@kaepora

I hung out over at #33 and it became apparent that two separate issues became confused, so I'll try and unravel.

At #33 32bit was assumed to be tethered to Windows application. There's a primary reason that can't work, and it isn't the Squirrel auto-updater. It is that Windows in 32bit going forward is and will be a treacherous security hole. Indeed, developers should obviate Windows 32bit work (unless they're going to work for ReactOS or something).

Linux in 32bit is an entirely different paradigm and continues to be kept up to date and viable and will continue to be. Linux also doesn't need an auto-updater.

So I'm hoping to prevail upon the CrCat team to reconsider the status of this bug as it was posted. 32bit can safely be abandoned in Windows. But all the other arguments in favor of that architecture over at #33 are pretty durable in the context of Linux, which is what this bug was actually for.
