### ISSUE TITLE
Issue when connection loss

### ISSUE THREAD

**Issue by Flo5701** [cryptocat/cryptocat#150]
when i lose connection cryptocat doesn't quit or reconnecting. Ma list of buddy is still yellow but if i clic in one of my buddy, chat windows doesn't pop.
I must disconnecting and reconnecting cryptocat for chat with my buddy

**Comment by kaepora** [comment]
@Flo5701 What OS and Cryptocat version are you using?

**Comment by Flo5701** [comment]
3.1.25 and OSX 10.11.5 in macbook pro, my issue come when i close my laptop

**Comment by kaepora** [comment]
Fixed in #161, I think.
