### ISSUE TITLE
Music recommendations

### ISSUE THREAD

**Issue by kaepora** [cryptocat/cryptocat#155]
Under the *Help* menu, add a *Music Recommendation* option. Clicking it opens a small dialog that displays my current music recommendation for Cryptocat users.

Genres will largely be limited to classical, piano, electronic, and progressive rock music. Recommendations will be changed once every week or so.

Really, why not?

**Comment by g0ldPRO** [comment]
> Really, why not?

Since you asked. Because no one gives a damn about what the developer of the chat listens to.

**Comment by kaepora** [comment]
Reaction to this issue has been hilarious. Four thumbs down!

**Comment by kaepora** [comment]
Okay, fine. I won't add complexity to the codebase so I can share my taste in music for everyone.

You spoilsports.

**Comment by TumM0reNcE5SsIti** [comment]
_Shame...really thought this one was going to take off. Maybe...music.crypto.cat? :m :o :o: _
