### ISSUE TITLE
Can't get the login screen to come up

### ISSUE THREAD

**Issue by vagoesham** [cryptocat/cryptocat#156]
i have installed the update, then had to uninstall and reinstall crypocat.  Can't seem to get the login screen to come up.  went to the menu bar and can't do anything unless I'm logged in but can't get to the login screen.  What can i do?

**Comment by kaepora** [comment]
Please be more specific. Provide version numbers, operating system, screenshots, details of your installation process, and so on. I can do absolutely nothing with what you've given me.

**Comment by zeecho** [comment]
This bug seems to also happen to a friend of mine on OS X Yosemite, cryptocat 3.1.26

**Comment by kaepora** [comment]
Cannot reproduce, sorry.
