### ISSUE TITLE
Time in chat says AM instead of PM

### ISSUE THREAD

**Issue by matthewmummert5** [cryptocat/cryptocat#158]
![bug](https://cloud.githubusercontent.com/assets/10691984/16638657/d1e02104-439d-11e6-9441-5492ffc7abb7.PNG)

The times circled in RED should say PM, but it says AM.

Steps to reproduce:

1. Send a chat to someone before noon and do not close the chat window
2. Send another message to that person after noon in the same chat window

Edit: Cryptocat Version -- 3.1.26

**Comment by kaepora** [comment]
How odd. Will look into it.
