### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Tamasss21** [cryptocat/cryptocat#159]
![1](https://cloud.githubusercontent.com/assets/20367509/16707343/4a0a749e-45ca-11e6-8024-d7bc8018e99b.jpg)
![2](https://cloud.githubusercontent.com/assets/20367509/16707346/50dd12b8-45ca-11e6-876e-59ff0e2fbdde.jpg)
![3](https://cloud.githubusercontent.com/assets/20367509/16707347/53bf8aec-45ca-11e6-8cba-31cacfe6f5f5.jpg)
![4](https://cloud.githubusercontent.com/assets/20367509/16707349/55818538-45ca-11e6-88d5-f466c02b18fe.jpg)
![5](https://cloud.githubusercontent.com/assets/20367509/16707350/579cb7de-45ca-11e6-8f12-0a4121031181.jpg)
![6](https://cloud.githubusercontent.com/assets/20367509/16707351/59885cce-45ca-11e6-8d67-cb7eff222ec1.jpg)
![7](https://cloud.githubusercontent.com/assets/20367509/16707353/5b459180-45ca-11e6-9bac-902ec75bbc33.jpg)
![8](https://cloud.githubusercontent.com/assets/20367509/16707354/5cfae0fc-45ca-11e6-9ec1-33e737a76b9f.jpg)
![9](https://cloud.githubusercontent.com/assets/20367509/16707356/5f24ffe8-45ca-11e6-9c9e-3742fc013ef2.jpg)

Hello, I am not troll, but I like bugs, and I think they are funny... You see, I found one.. This is a small bug, no more..  

Congratulations to the administrator, because I love this program and so cool.

I think if the users can speak with microphone in the future, this program become the best!

**Comment by kaepora** [comment]
What the hell is this? I'm opening a separate issue (#160) that isn't so ridiculously formatted.
