### ISSUE TITLE
Dragging/dropping files sometimes makes drag overlay get stuck

### ISSUE THREAD

**Issue by kaepora** [cryptocat/cryptocat#160]

**Comment by Tamasss21** [comment]
Dear kaepora!

I would like help for you, and I am hungarian --> I don't speak English very well, so I created many pictures from the bug.. No sometimes get stuck... Only if I try send twice ONE photo or file, but I think better of it, and I don't send it, the program get stuck. That's all.. Is this understand?

**Comment by kaepora** [comment]
I understand. Your bug is now fixed. Please wait until the next software update.

**Comment by Tamasss21** [comment]
Thanks... nice job!
