### ISSUE TITLE
Installation on 32bit Windows 8.1 Supported

### ISSUE THREAD

**Issue by betterlaef** [cryptocat/cryptocat#163]
When attempting an installation of CryptoCat on a Windows 8.1 32 bit system, Squirrel very helpfully gave this error:

`Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.ComponentModel.Win32Exception: The specified executable is not a valid application for this OS platform.`

Checking around on the Internet, this seems to be typically caused when the application that the user is trying to install is only for 64bit systems, yet the Windows zip is titled _Cryptocat-win32-x64_, which would lead me to believe that it's built for both. Am I incorrect here, or is it likely that something else could be causing this?

**Comment by kaepora** [comment]
See #33
