### ISSUE TITLE
Cryptocat: Cannot Check for Updates

### ISSUE THREAD

**Issue by tuxication** [cryptocat/cryptocat#167]
I got the Cryptocat: Cannot Check for Updates on startup using the latest 3.2.00 version. It connects normally to the server and I'm able to send/receive messages normally. This only happens on my Linux VM and works fine on other machines.

**Comment by kaepora** [comment]
This was a server side issue and is now resolved. You will not need to update for the bug to be fixed. Thanks for reporting.
