### ISSUE TITLE
Function to delete scroll window content with a button click and/or shortcut

### ISSUE THREAD

**Issue by gilles-leonard** [cryptocat/cryptocat#173]
I would like to see a function to delete scroll window content with a button click and/or shortcut. I work in the cybersecurity industry and there are sensitive information that we exchange with Cryptocat that I would rather have disappear from my screen as soon as it has been used. That function would come handy for that purpose. Having to close and re-open a session to get that result is naaah... not quite it!

**Comment by kaepora** [comment]
Not worth implementing. Just close your window.
