### ISSUE TITLE
Buddy List not opening. 

### ISSUE THREAD

**Issue by FredericJacobs** [cryptocat/cryptocat#18]
Following message appears when trying to open buddy list.

![screen shot 2016-03-30 at 11 05 56](https://cloud.githubusercontent.com/assets/400296/14137304/91f5e61a-f667-11e5-837f-2401782f14ec.png)

**Comment by kaepora** [comment]
When is this occurring? Every time?

How are you opening the buddy list?

Please provide a more complete description of your problem.

**Comment by kaepora** [comment]
I believe this is fixed in cd03360adb71d5bb0ebd9a0eae6d741629094a7d.

**Comment by mseltene** [comment]
For me, changing "closed" to "close" worked!
win.on('close', () => { win = null }
