### ISSUE TITLE
Send messages to trusted devices only by default

### ISSUE THREAD

**Issue by IpsmLorem** [cryptocat/cryptocat#185]
A part of the secuity rely on the manual verification of our buddy devices hash.
Cryptocat would be more secure with "Send messages to trusted devices only by default" turned on by default for every buddy.

Furthermore, Maybe a visual display around the buddy avatar could show if you have no device trsuted for that buddy.

The logic should be reversed : Trusted device only for everyone and not an option. An per buddy exception to choose to send even on untrusted device

**Comment by kaepora** [comment]
No.
