### ISSUE TITLE
Has Cryptocat changed the PGP signature again?

### ISSUE THREAD

**Issue by bungabunga** [cryptocat/cryptocat#189]
I can't verify the latest version of Cryptocat for Linux because it's signed with a different PGP key but I also can not find that public key on Cryptocat homepage to be able to trust it.

**Comment by kaepora** [comment]
Yes, the key has again changed... I'm sorry, I've been travelling a lot all summer and I keep having to do some black magic on my laptop often without reliable backups.

The new key is indeed available [here](https://crypto.cat/help.html#signatures).

I'm aware that's like, three PGP key rotations in 4-5 months, I'll try and make sure it doesn't happen again.
