### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Ashtor** [cryptocat/cryptocat#19]
1. Status Message where we can make Our own status Message (like skype-like status Message)
2. Anonymous login (optional. wich means People can decide if they want to login being anonymous or With password)
3. Nick change (like the old cryptocat had.. not necessary)
4. Busy,available and away system (green status: Available,Yellow status: Gone,Red status: Busy)
5. Clickable links
6. Fonts and colours option when texting
7. Markdowns to make texts bold,ittalic,strikethrough and underline

**Comment by kaepora** [comment]
Please do not open general tickets like this. Tickets should address specific issues. Also, please try to avoid duplicates.

**Comment by Ashtor** [comment]
Sorry for posting this,but no idea where to post suggestions,so I got to ask.. where do I send suggestions for the New rewrite and how?
