### ISSUE TITLE
macOS: Unable to open closed "Contacts" window

### ISSUE THREAD

**Issue by laasp** [cryptocat/cryptocat#194]
**Case:**
- open mac CC client
- close the contacts window from red X (or cmd + w)

**Problem:** It's not possible to open the contacts windows again without restarting the client.

**Suggestion:** Usually mac apps have "Window" drop-down menubar item where different program windows can be opened.
For Cryptocat this would be between "Edit" and "Help" menus.

![contacts_no_open](https://cloud.githubusercontent.com/assets/700222/18288164/f10c799a-7482-11e6-8f66-d2035b6f6c96.jpg)

**Comment by kaepora** [comment]
Confirmed bug. Will push a fix soon. Thanks for reporting.

**Comment by kaepora** [comment]
Fixed in 8b7fc2b2b3d7323453dc2883ef1e01ab4c66b3ec.
