### ISSUE TITLE
Offline messaging

### ISSUE THREAD

**Issue by Fella1** [cryptocat/cryptocat#195]
Offline messages are not going through.
I have had several instances - both ways - where messages have been sent and are never received by either party.
I note from the faq page
"When you send a message, your message will be half-transparent and fade into fully opaque once it's actually sent to the server. Messages that remain transparent or turn red may have not been sent". 
The messages (after being sent) are a salmon pink colour.
Is there a workaround for this?
thanks
![capture](https://cloud.githubusercontent.com/assets/22077890/18352208/5bca6b04-75d5-11e6-8c21-925fec60343f.PNG)

**Comment by kaepora** [comment]
Cannot reproduce.
