### ISSUE TITLE
Prevent "Cannot check for updates" from appearing ~2 seconds after starting the computer

### ISSUE THREAD

**Issue by Dyras** [cryptocat/cryptocat#196]
Hello. I'm going to keep this simple.

I have a really fast computer, and a not so fast router. It takes a couple of seconds for me to get online whenever I start my computer because of this, 15 seconds or so I'd say. Ordinarily this is fine, but since my computer is so damn fast (login is almost instantaneous, for example), I'm always. ALWAYS greeted by this crap:
![image](https://cloud.githubusercontent.com/assets/12563436/18366686/fb149be8-7617-11e6-9421-369b8545f210.png)

Now if you ask me, I think it should take into consideration that some routers just plain suck and that it takes a couple of seconds to go online.

I have a Cryptocat shortcut in my Autostart, which is how I have it set up to start immediately. I realize I could use a program to delay the startup, but I still think this is big enough of an annoyance to be fixed. Maybe Cryptocat should try to check for updates once a minute for 10 minutes before complaining?

**Comment by kaepora** [comment]
@Dyras I can't reproduce this. Please make sure you are using the latest version of Cryptocat by re-downloading it from the website.
