### ISSUE TITLE
chat error

### ISSUE THREAD

**Issue by joeblow1120** [cryptocat/cryptocat#199]
every time i am chatting i get the following message.

This message could not be decrypted. You may want to ask your buddy to send it again.

this happens over and over again.  Makes using the program useless and frustrating.

**Comment by nimd4** [comment]
... Wanna add me & we can check it out together? :o

What OS are you (both) using, I'm on Windblow$ (Enterprise 10 N LTSB), 

> PS C:\Users\*******> [environment]::OSVersion.Version
> Major  Minor  Build  Revision
> -----  -----  -----  --------
> 10     0      14393  0       
> 
> PS C:\Users\*******> 

^^ Because, maybe, it's a cross-version, OS, thing? o.0

**Comment by kaepora** [comment]
@nimd4 Has been banned from posting on future issues pursuant to this comment also comments on #198 and #154.

**Comment by kaepora** [comment]
Cannot reproduce, unhelpful issue report. Please make sure both you and your buddy are using the latest version of Cryptocat.

In the future, please actually read the guidelines in order to understand how to helpfully report an issue.

**Comment by Alchimicus** [comment]
Still with this bug... Happens always in the second message after add a buddy... Me and my buddies are using linux, if this helps.
