### ISSUE TITLE
Help documentation: "Your identity keys" = "fingerprints"?

### ISSUE THREAD

**Issue by cw337** [cryptocat/cryptocat#201]
The [Help documentation](https://crypto.cat/help.html) introduces the term "fingerprints" in italics in the section "Verifying your Buddy's Fingerprints". Then in the next section "Managing Devices Safely" it uses the term "identity keys". Are these referring to the same thing? If they are, they should use the same term for clarity.

**Comment by kaepora** [comment]
No, they're not. Identity keys are special private keys that are stored locally on your device. Fingerprints are a public identifier that is used to identify a set a identity keys.
