### ISSUE TITLE
Can no longer share files or pictures in Cryptocat

### ISSUE THREAD

**Issue by kathysue** [cryptocat/cryptocat#204]
![error](https://cloud.githubusercontent.com/assets/22350001/18753424/e1b7da00-80aa-11e6-898a-55ce7a1a91aa.jpg)
### Reporting Bugs
If you are reporting a bug, please consider the following questions first:

* Can you reliably reproduce the bug you are reporting? Are you sure your description is accurate?

YES

* Will the Cryptocat developers be able to reproduce your bug? What information will they need?

IF they try.  

When dragging and dropping or using the send file icon, I get the same results

### Proposing Enhancements
If you would like to propose an enhancement, first consider:

* Is your enhancement's value almost entirely subjective (change Cryptocat's color scheme to your favorite color, etc.)? If so, please do not open a new issue.
* Is your enhancement only valuable to your specific use-case or would it be useful to a general base of Cryptocat users? Please do not open a new issue if the former case applies.
* Can your proposed enhancement be described in concrete steps? Does it fit well with the current architecture?

### Other Issues
General questions are somewhat welcome on the issue tracker, but please limit your discussions to outside the scope of your personal opinion as much as possible. Your personal views on a feature are a waste of time. Consider rather how a feature or change would affect the software's consistency and its viability towards its larger userbase.

**Comment by morloy** [comment]
Same here, I guess.
https://crypto.cat/sas seems dead.

**Comment by kathysue** [comment]
Glad to know I am not by myself.

I added to my comments.

Kathy



----- Original Message -----

**Comment by Dyras** [comment]
Same here! So, does it actually work for some people? Or is it down for everyone?
http://img02.imgland.net/6x_uRu.png

**Comment by barnstws** [comment]
Same error with older versions.

**Comment by cahuja** [comment]
I am getting this error as well.

**Comment by kaepora** [comment]
Sorry about this, it was a server issue and is now resolved.

**Comment by barnstws** [comment]
It's happening again. Can't send files again.
