### ISSUE TITLE
When clicking "learn more" during device authentication, cryptocat is closed

### ISSUE THREAD

**Issue by friedhelmweinberg** [cryptocat/cryptocat#21]
When I click learn more during the initial device setup, my browser opens the Cryptocat website - at the same time the application is closed. At least for me, expected behaviour would be that the Cryptocat remains open.

This happened on Ubuntu 15.10.

**Comment by friedhelmweinberg** [comment]
Thanks!

**Comment by kaepora** [comment]
You're welcome. Thanks for using the software.
