### ISSUE TITLE
[macOS] Cryptocat prevents sleep

### ISSUE THREAD

**Issue by ejpcmac** [cryptocat/cryptocat#211]
## Problem description

When I usually ask my Mac to sleep, the process takes 4-5 seconds. If Cryptocat is open, the process takes 30 seconds instead.

In the system logs I can see, 30 seconds after the sleep process starts:

    kernel[0]: PM notification timeout (pid 13893, Cryptocat)

So it seems Cryptocat is preventing macOS from sleeping in some way.

## Expected behaviour

Cryptocat should not delay the sleep process.

## Configuration

* **OS version:** OS X Yosemite 10.10.5
* **Cryptocat version:** 3.2.07

**Comment by kaepora** [comment]
I now have a Mac, so testing for this should be easier.

**Comment by kaepora** [comment]
Very sorry, but I honestly can't reproduce this.

**Comment by kaepora** [comment]
It might have to do with Electron, which I've recently updated to the most recent version. Let's see if this occurs when I push a Cryptocat update using an updated Electron.

**Comment by ejpcmac** [comment]
Ok, I’ll tell you after the next update.

**Comment by kaepora** [comment]
@ejpcmac Excellent.

**Comment by kaepora** [comment]
@ejpcmac What's the word, chief?

**Comment by ejpcmac** [comment]
@kaepora Same problem with Cryptocat 3.2.08 on OS X Yosemite 10.10.5. I did not test on another Mac than mine though.

**Comment by kaepora** [comment]
Yosemite's ancient. Update your OS first.

**Comment by ejpcmac** [comment]
I’ll try to get an El Capitan image (not possible anymore from Apple, and Sierra is not compatible for the moment with a few importants things I use) and let you know.
