### ISSUE TITLE
Require Current Password Before Changing Password

### ISSUE THREAD

**Issue by TumM0reNcE5SsIti** [cryptocat/cryptocat#212]
I change my password frequently, and though it's a feature to change your password without needing your original, I feel like this is a fundamental flaw in the security of an account while logged in.

You should be required to identify yourself, with at least a single factor, before changing the password. Logging in shouldn't be that factor. Not everyone locks their computer. And for those that don't, this is a fundamental security flaw, exposing any person, to allow a password change if they recognize the application running. Especially with no recovery method if the account password is changed.

Consider the following scenario instead:
**Old Password:
New Password:
Confirm Password:**

**Comment by kaepora** [comment]
No. Being logged in is enough.
