### ISSUE TITLE
Launcher icon on Ubuntu is not using the Cryptocat logo

### ISSUE THREAD

**Issue by friedhelmweinberg** [cryptocat/cryptocat#22]
In the Ubuntu Unity launcher, the Cryptocat logo is not used, but only the default question mark. The logo does show up on the top right menu, however.
![cryptocaticon](https://cloud.githubusercontent.com/assets/7205036/14143148/f32b0b1e-f689-11e5-8411-7d0cd7d9c88f.png)

**Comment by kaepora** [comment]
How can I fix this?

**Comment by friedhelmweinberg** [comment]
Unfortunately, I don't know - someone else from the community has an idea? Thanks for responding so swiftly to all issues and, of course, for building Cryptocat as free software.

**Comment by kaepora** [comment]
You're welcome. I'm afraid that I actually use Fedora with Xfce, so I have no way of testing out integration on Ubuntu's Unity desktop environment. For what it's worth, the Cryptocat application folder on Linux has a logo.png file that you might be able to use to customize the icon for your Unity menu entry. I've never used Unity in my life though, so I can't say for sure.

**Comment by friedhelmweinberg** [comment]
Thanks, does not seem to work, so if anyone else has an idea that would be greatly appreciated.

**Comment by tuxication** [comment]
I managed to manually add the icon to the Unity launcher but I'm not sure how do it automatically. I created a desktop file and add it to /home/user/.local/share/applications/cryptocat.desktop.

This is the content of the file:
[Desktop Entry]
Name=Cryptocat
Exec=/home/user/Cryptocat-linux-x64/Cryptocat
Icon=/home/user/Cryptocat-linux-x64/logo.png
Terminal=false
Type=Application
Categories=Utility;Application;

**Comment by kaepora** [comment]
@tuxication This is very helpful, thanks.

**Comment by friedhelmweinberg** [comment]
Thanks, works now with latest version! Very happy to see the icon in the launcher.
