### ISSUE TITLE
Operating system name?

### ISSUE THREAD

**Issue by andersbateva** [cryptocat/cryptocat#223]
I don't know if this would be seen as a privacy and security concern, but would be feasible to show the buddy's device OS? Not necessarily read system info, not even show specific version of the OS, but if the installed Cryptocat are the Windows, Linux, or Mac files (as downloaded from the site).

The problem is: Windows 10 sends to the Microsoft servers every key pressed. What's the purpose of using E2E encryption, if, on the buddy device, every key it presses is logged, sent to Microsoft, stored and analyzed. All the connection was protected, but the data was captured before being encrypted! So, half of the chat is guaranteed to be captured if the buddy uses W10. I would not be surprised if someday it's revealed the other half can be captured too similarly.

Knowing the buddy is using Windows could help the more concerned about this matter to un-buddy the Windows user, as it's helping the surveillance by using this OS. On Telegram I ask people which OS they run the client, but it's much more work-intensive and the buddies can lie or refuse to answer.

**Comment by kaepora** [comment]
No.
