### ISSUE TITLE
Sending files and video does not work 

### ISSUE THREAD

**Issue by hurrdurr123** [cryptocat/cryptocat#251]
For the last few days, sending videos and files has not been working. I get a warning saying "Cannot Send File. Video.webm. could not be sent. The file type could be unsupported or there could be a network error."

**Comment by Gawinda** [comment]
Hello, same problem here! Sending images worked fine two weeks ago, but today I get the "Cannot send file..." message. Tested .txt and .jpg

**Comment by Sandriell** [comment]
Same issue, same error, no matter what type of file I try to send.

**Comment by kaepora** [comment]
This was fixed.
