### ISSUE TITLE
Files not being Sent or Received on linux, DNS request to crypto.cat instead of cryptocat.blob.core.windows.net

### ISSUE THREAD

**Issue by cryptocatuser341** [cryptocat/cryptocat#261]
On various linux distros( including fedora, debian, ubuntu, and arch) using the source code instead of the appimage (npm run dev), files are not being sent or received. The typical upload animation and icons are not displayed at all on sender or receiver end. Looking at network activity, it shows that once the file is attempted to be sent, CCat runs a DNS query for crypto.cat, which is the chat server. cryptocat.blob.core.windows.net is never seen in this network traffic. Sending a picture or video also has this problem using this dev version. Everything is up to date, and chat works excellent.  Love the chat application, thanks for taking the time to work on it.

**Comment by kaepora** [comment]
Cannot reproduce. Likely a temporary network error.
