### ISSUE TITLE
Feature Request: Allow login with accounts not on crypto.cat domain

### ISSUE THREAD

**Issue by iNPUTmice** [cryptocat/cryptocat#28]
Since cryptocat in it's core is an XMPP client it would be nice if we could use cryptocat with XMPP accounts not on the crypto.cat server.

**Comment by kaepora** [comment]
I am currently not interested in this. I understand the arguments for allowing multiple domains, but I do not agree that they are the correct direction for *this* project. Having a single domain allows users to add each other without much confusion, in a similar setup to something like Twitter. Having multiple domains will introduce user experience confusion that is inappropriate for a project like Cryptocat.
