### ISSUE TITLE
No devices listed during the first login

### ISSUE THREAD

**Issue by DaniSancas** [cryptocat/cryptocat#29]
I think it's not very important but, during the first login, after adding the device where you are connecting from (my PC in this case) will not appear in the "Manage Devices" window during the first login. If you quit and re-login again, then you will see your device.

**Comment by kaepora** [comment]
Thanks. Fixed in a8920bb4b5f55b1f00668aaf5bedf0d0c207dff6.

**Comment by DaniSancas** [comment]
Very fast response! Thanks to you! :+1:
