### ISSUE TITLE
Server sources

### ISSUE THREAD

**Issue by hurlebouc** [cryptocat/cryptocat#30]
Hi there! Concept of cryptocat is very pleasing, but it still rely on a central server. Is it possible to install its own instance of the server? Is the server source code published somewhere?

Thank you for your job!

**Comment by kaepora** [comment]
Here you go: http://prosody.im/source/start

**Comment by hurlebouc** [comment]
Is prosody is enough for Signal Protocol: for instance, how are handled prekeys? Is there nothing new compared to XMPP?

**Comment by iNPUTmice** [comment]
> Is prosody is enough for Signal Protocol: for instance, how are handled prekeys? Is there nothing new compared to XMPP?

Cryptocat uses the [OMEMO encryption](https://conversations.im/omemo) which was designed to work with existing XMPP servers. Basically every modern XMPP should do.
