### ISSUE TITLE
Can't gpg verify Cryptocat.zip in Ubuntu

### ISSUE THREAD

**Issue by bungabunga** [cryptocat/cryptocat#31]
When i try to verify the signature on Ubuntu 15.10 with gpg --verify/gpg2 --verify i get this response: "Can't check signature: Invalid public key algorithm."

**Comment by kaepora** [comment]
Could you please paste the output of `gpg2 --version`?

**Comment by kaepora** [comment]
Please update to `gpg2 2.1.11` or higher.
