### ISSUE TITLE
Switch to 32-bit builds

### ISSUE THREAD

**Issue by TokumeiNanashi** [cryptocat/cryptocat#33]
After downloading and running the setup executable, the CryptoCat icon appears briefly in the center of the screen before an error message appears:

"Installation has failed
There was an error while installing the application.
Check the setup log for more information and contact the author."

I am attaching the setup log, but due to this being Japanese Win 7, some log messages will not be in English.

**Comment by Ashtor** [comment]
As far as I can tell and know,the cryptocat only works on 64 bit

**Comment by Ashtor** [comment]
Thats all I can tell

**Comment by kaepora** [comment]
32 bit is not supported.

**Comment by TokumeiNanashi** [comment]
I figured that might be the case, but I couldn't find any system requirement information on the landing page so I wasn't sure. Thanks for the confirmation. It might be a good idea to list the system requirements on the download page to avoid confusion.

Thanks again.

**Comment by Ashtor** [comment]
Thats a good idea.. mention it to nadim (or kaepora) about it.. U can always ask in this forked cryptocat (forked cryptocat edited from the old cryptocat): cryptodog.github.io/cryptodog .. If u still cant fix it,just ask nadim/kaepora

**Comment by TokumeiNanashi** [comment]
It's looking like New CryptoCat won't be supporting 32 bit, so personally I think I'll move on to greener pastures, at least until I'm using a 64 bit OS. Cryptodog is amusing, but given the self-confessed security holes on their part I'll pass on it for now. Thanks.

**Comment by kaepora** [comment]
@TokumeiNanashi I'm sorry you can't use the new software. My reasoning is that since 32 bit is a clearly obsolete platform being used by a small minority, it doesn't make sense for me to double the complexity of my build/signing/update pushing process simply to accommodate it across Windows, Linux and Mac. The effort isn't worth it.

I suggest you upgrade to 64-bit processor and hope you'll give it a shot. You'll have to go out of your way these days to stick to a 32-bit machine; they're increasingly hard to find and out of the mainstream.

**Comment by TokumeiNanashi** [comment]
@kaepora Thank you for the response. While what you're saying might be true in the Western world, I'm based in Japan, which is generally quite behind the curve when it comes to home computing (to give you an example, Internet Explorer remained the most popular browser of choice nationwide up until Win 10 replaced it with Edge... ask a web developer with work experience in Japan and watch them cry). Things are starting to change, but as with all things in Japan it's happening slowly.

I was using CryptoCat with a team of locals, and over half of them are on 32-bit systems. Until everybody is using a 64-bit system, I'm afraid we'll need to consider other options in the short term. In the long term I hope we can come back. I was quite fond of the program, and hope to use it again.

Thank you for your hard work, and good luck with the new version.

**Comment by kaepora** [comment]
@TokumeiNanashi This is pretty odd. Thanks for the perspective, I hope things will change shortly in Japan. In the meantime I will consider maintaining 32-bit builds.

**Comment by TokumeiNanashi** [comment]
@kaepora I hate to feel like I'm pushing to add to your workload or anything... I do think you're right, 32 bit is on the way out. Japan's just unusually slow on the uptake.

Anyway, thanks again. I really appreciate all the work you put into this.

**Comment by edhelas** [comment]
@TokumeiNanashi Cryptocat is actually a XMPP client with OMEMO enabled, the old version was a XMPP client with OTR enabled. If you want to have quite the same system I recommend you to install Gajim (https://gajim.org/downloads.php) or Conversations on Android that also got the same features.

**Comment by kaepora** [comment]
@TokumeiNanashi Don't feel bad. I'm always happy to consider how to make things better for users, so long as these considerations fall in line with the project's mission and what is sensible for users.

**Comment by bungabunga** [comment]
i'd also love to see 32bit builds, i got my son a raspberry Pi box to use it as a light internet computer since i couldn't afford him a real pc and the Raspbian OS (based on Debian) is 32bit only for now.

**Comment by kaepora** [comment]
@bungabunga Raspberry Pi is actually a special architecture (called ARM) that's not exactly the same 32-bit as regular computers (x86).

**Comment by bungabunga** [comment]
would you consider adding Arm/Raspbian build? the platform is quite popular. i didn't want to make a separate issue bc i don't want to spam too much here.

**Comment by kaepora** [comment]
@bungabunga Yes, I'll do that at some point.

**Comment by ghostlands** [comment]
I think developers keep forgetting developing countries, ironically. I'd like to be mistaken, but I don't think staying up to date hardware-wise is necessarily easy in less affluent parts of the world.

**Comment by Shadeclan** [comment]
It's not just Japan.  Many people, especially governmental agencies, are still on 32 bit platforms.  I work for New York State ITS and we're still on 32 bit platforms.
It may be a moot point for me, however.  The place I need an application like CryptoCat is at work.  The old CryptoCat was great because I could use it through my browser.  All IM ports are blocked here so, without a browser app like CryptoCat, I'm out of luck.

**Comment by kaepora** [comment]
Alright, alright. I'm switching to 32-bit builds.

**Comment by Shadeclan** [comment]
Many Thanks.

**Comment by kaepora** [comment]
I am sorry to report that after investigating this issue, it appears that a fix is not currently possible since the Electron framework's Squirrel auto-updater is 64-bit only on Windows. As such there will be no 32-bit releases of Cryptocat.
