### ISSUE TITLE
Can't import gpg key in Ubuntu with gpg2

### ISSUE THREAD

**Issue by ethannorth** [cryptocat/cryptocat#41]
Hi Nadim, I didn't respond in time and the issue was closed - sorry, my bad! Here is the issue again with you question answered. Thank you for building this and for taking the time to address my question.

I copied the key into vim and saved the file as cryptocat.asc, then ran:

gpg2 --import cryptocat.asc
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0

Output from gpg2 --version is:

gpg (GnuPG) 2.0.22
libgcrypt 1.5.3
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: ~/.gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA, ?, ?
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: MD5, SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2

**Comment by kaepora** [comment]
As noted in my original answer to you in #32, make sure you are running the latest version of `gpg2`, ergo `2.1.11` or higher.

Instead of hailing my advice, you chose to waste my time by opening a duplicate issue for the same problem. Do not do this.
