### ISSUE TITLE
Login stall when proxy does not authorize the request

### ISSUE THREAD

**Issue by starbuck3000** [cryptocat/cryptocat#43]
Observed:
1) Authenticate through a proxy that requires authentication (configured in Windows settings),
2) The proxy responds with an HTTP code 407 response,
3) The login button label remains in italic and stalls.

Expected:
3) The login button label should return to normal and a prompt showing that the authentication could not be performed.

**Comment by SparkDustJoe** [comment]
I have also observed this behavior on flaky networks that connect and disconnect a lot (such as open- or guest-WiFi), the login seems to take forever but never actually completes.  There is no opportunity to attempt to login again until the program is completely closed and reopened.  (as in quitting, not simply minimizing)

**Comment by kaepora** [comment]
I can reproduce this, will investigate and fix.
