### ISSUE TITLE
Sign binaries on website?

### ISSUE THREAD

**Issue by taoeffect** [cryptocat/cryptocat#44]
Website should have signatures for all binaries + gpg key used to sign them, but I can't seem to find it:

https://crypto.cat/

**Comment by taoeffect** [comment]
I recall that Peerio used to have instructions for verifying signature using `codesign` + the fingerprint, but...

- That isn't on the cryptocat website
- Requires users to have to install Xcode
- Is awkward as for it to be truly effective your public key should be saved by users locally somewhere, and GPG automates that. Here a user would most likely download the app and if they were to check the signature they would look at the fingerprint on the website at the same time, which is roughly equivalent to TLS-level security (i.e. the same as listing a SHA256).

**Comment by taoeffect** [comment]
Speaking of which, I can't try the app itself out until I know what the hash/sig is supposed to be. Would be cool if at least in the meantime that info could be posted here.

**Comment by kaepora** [comment]
> I recall that Peerio used to have instructions for verifying signature using codesign + the fingerprint, but...
> That isn't on the cryptocat website

[Yes, it is.](https://crypto.cat/help.html#signatures).

> Requires users to have to install Xcode

No, it does not.

> Is awkward, as for it to be truly effective your public key should be saved by users locally somewhere

The automatic updater included in Cryptocat does [something even better](https://crypto.cat/help.html#signatures).

I appreciate that you're trying to contribute, but you come across as loud, ranting and unhelpful. You will be blocked from this issue tracker if you again open (multiple) tickets without having actually read the documentation. You are wasting my time.
