### ISSUE TITLE
package.json deps should specificy precise version numbers (and preferably be bundled)

### ISSUE THREAD

**Issue by taoeffect** [cryptocat/cryptocat#46]
As a maintainer of multiple node.js projects, I know that having the deps say `"latest"` guarantees that cryptocat will break for people at some point (in the not too distant future).

Better to create an `.npmrc` in the root with `save-prefix = ''` and install precise version numbers. Even better would be to bundle the dependencies within the project itself to decrease the risk of compromise.

To stay up-to-date with deps you can run `npm outdated` and filter it and use that as part of your tests, and/or include one of those `depencencies` image tags in your README.md.

[Retire.js](https://github.com/RetireJS/retire.js) can be used to automatically alert you of vulnerabilities in dependencies and it has a [grunt-retire](https://github.com/bekk/grunt-retire) task.

**Comment by kaepora** [comment]
If you look closely, you will notice that most dependencies are indeed already bundled with the project. The very few that aren't (only two) are fetched via `npm` for a reason, and rest assured that I am maintaining their CI via my testing and release scripts.
