### ISSUE TITLE
Chats fail after a few hours

### ISSUE THREAD

**Issue by zl3ai** [cryptocat/cryptocat#49]
With two Win 10 laptops running version 3.0.24 sitting side by side, chats between them would fail after a few hours even though the displayed statuses said each was online. Status continued to say 'online' even after other the laptop was switched off.

**Comment by kaepora** [comment]
Odd. Will look into it.

**Comment by kaepora** [comment]
Odd. Will look into it. Are you disconnecting at all during these hours? Might be a re-connection failure.

**Comment by zl3ai** [comment]
I began chatting back and forth, then left it alone for a few (2 or 3?) hours,  and then when I typed some text and sent it, it didn't appear on the other computer even though the status box was blue reporting the other computer was online.

I just checked now and the other computer is still shown as being online, even though it was switched off 18 hours ago.

**Comment by kaepora** [comment]
This should be fixed in 3.0.30, which will be released shortly. If it's not, please comment here and I will reopen this issue.
