### ISSUE TITLE
Updater stuck in loop.

### ISSUE THREAD

**Issue by FredericJacobs** [cryptocat/cryptocat#5]
I've tried a few times to update on one of my devices, a Mac.

When I launch it, it prompts me for a download location. I selected my downloads folder. It says it will relaunch. After relaunch, I still get asked to update.

I did try a few things, including deleting previous updates from my download folder, thinking the issue would be overwriting the previous .zip. But that's not it.

Let me know if you need extra debugging info.

**Comment by kaepora** [comment]
Cryptocat only downloads and verifies the signature of the update installer. You still need to go to your downloads folder and run the installer manually. This is explained in the dialog box that is shown when the update download is complete.
