### ISSUE TITLE
File transfer: progress bar should disappear once transfer is completed.

### ISSUE THREAD

**Issue by ggramaize** [cryptocat/cryptocat#53]
Tested version: 3.0.27
Reproduction path:
1. Open chat window
2. Send file

Once the transfer is complete, the progress bar should disappear, as its presence suggests the transfer is stuck on the final step.

![xfercap](https://cloud.githubusercontent.com/assets/5450075/14411702/20a9708e-ff50-11e5-9638-ef755f8a918d.png)

**Comment by kaepora** [comment]
This is reasonable. Will add.

**Comment by kaepora** [comment]
I won't remove the progress bar, but I'll make it turn green.
