### ISSUE TITLE
Cryptocat 3.0.29 - gpg: Can't check signature: Invalid length

### ISSUE THREAD

**Issue by bungabunga** [cryptocat/cryptocat#57]
It's not possible to check signature for the latest release on Ubuntu 16.04:

> gpg: Signature made sre 13 apr 2016 02:37:50 CEST using EDDSA key ID 5D93C3CB
gpg: Can't check signature: Invalid length

Checking signatures of previous versions works fine.

**Comment by kaepora** [comment]
You already complained about this, and I already answered your question (#31).

**Comment by kaepora** [comment]
My apologies! This indeed seems to have cropped up in the latest release. Investigating.

**Comment by kaepora** [comment]
Fixed for next release. Thanks, and sorry again for shooting this down earlier. I get too many duplicates and it's jaded me a bit.

**Comment by bungabunga** [comment]
yeah, i can unerstand your feelings. ;)
