### ISSUE TITLE
Login button stays disabled

### ISSUE THREAD

**Issue by FsecureSamiTikka** [cryptocat/cryptocat#59]
I just launched Cryptocat for the first time (3.0.30)
I clicked on the button "Create account" and created an account on a web page that was opened.
Now I enter the username and password to Cryptocat but the Login button stays grayed out and I cannot click it.
I am using OS X 10.10.5

**Comment by kaepora** [comment]
I can't reproduce this, although I've tried different times on both Linux and El Capitan. I don't understand why it would happen with you. Does relaunching the client resolve the problem?

**Comment by kaepora** [comment]
Nevermind, I can reproduce it! I have a good idea what the problem might be.

**Comment by diracdeltas** [comment]
Having the same issue on master, OS X 10.11.4. Click create account, made an account, clicked login, login button stays disabled indefinitely and nothing happens. Cryptocat also won't close after the login button is disabled and I have to force-quit it.

relaunching does not solve the problem

clicking 'Log out' in the app menu says I must be logged in to perform this action, so seems that login did not succeed

**Comment by kaepora** [comment]
OK, this seems to be OS X specific. I'll take a look. Are any of you running some weird antivirus? Firewall? Little Snitch? Anything of the sort? If so, try disabling it for a second and logging in again?

**Comment by kaepora** [comment]
Okay, did some testing with @diracdeltas and figured it out. Will push fix tomorrow.
