### ISSUE TITLE
grunt mac build: Could not connect to Cryptocat. Please try again.

### ISSUE THREAD

**Issue by sighmon** [cryptocat/cryptocat#61]
I followed the build instructions on OS X 10.11.4 using Homebrew node v5.10.0 & npm v3.8.6, and get these warnings at ```$ npm install```:

```npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.```
```npm WARN grunt-exec@0.4.6 requires a peer of grunt@~0.4 but none was installed.```

```$ grunt mac``` builds without errors or warnings.

But then I can't connect. Any suggestions?
![screen-shot-2016-04-15-at-12 20 39-pm](https://cloud.githubusercontent.com/assets/314298/14550144/4ccc7964-0305-11e6-8838-63d4671ebb29.jpg)

**Comment by kaepora** [comment]
This isn't a support forum. Please only open issues pertaining to specific, reproducible bugs.
