### ISSUE TITLE
Valid password from website failed to login on mac app

### ISSUE THREAD

**Issue by sighmon** [cryptocat/cryptocat#62]
Apologies for my previous build issue #61 - I kept testing with a new user, and it was a problem with the password I created initially. I made a 31 character passphrase which included these characters:

``` [\]&##()( ```

Logging in failed.

Then I made another just with uppercase, lowercase, digits and dashes, and that logged in without problem.

**Comment by kaepora** [comment]
This is a valid bug. Will investigate and fix. Thanks.

**Comment by kaepora** [comment]
Cannot reproduce. I tried creating an account with the password `[\]&##()([\]&##()([\]&##()([\]&` and I was able to log in just fine.

Please don't open issues for bugs unless you're sure it's not due to user error.
