### ISSUE TITLE
Explore Alternative Fingerprint Verification Strategies

### ISSUE THREAD

**Issue by sarciszewski** [cryptocat/cryptocat#627]
This is probably a really low priority suggestion, but I think it could open the door to better usability for privacy-assuring software.  Since part of Cryptocat's mission is usability, this seems like the best place to post it.

Right now, fingerprints are verified by comparing hexadecimal strings or by the socialist millionaire protocol. I believe fingerprints could be implemented better (although it's debatable how much better).

Some ideas:
* One strategy is to use the fingerprint to display a series of colors to the user. (I believe this one was actually used before.)
* Another would be to display a series of simple, visually distinct graphics and use the fingerprint to replace the colors in the photo (I call this the false color strategy).
* Using the fingerprint to generate a short serious of distinct musical tones may be helpful as well.
* Finally (as a derivative of the previous idea), there may also be some value in affecting the tone that each message plays in a way that is derived from the fingerprint (though this might only be useful for when the long-term authentication is deployed).

These are merely ideas, not specific suggestions.

**Comment by sarciszewski** [comment]
Closing because cryptocat is collecting dust and apparently @kaepora has moved onto bigger and brighter projects.

**Comment by RaedsLab** [comment]
This reminds me, I have done a little test here : http://lab.raed.tn/iconify/

It is not that "efficient" but it is jut a try
