### ISSUE TITLE
Complete inability to send or receive any message

### ISSUE THREAD

**Issue by mafster** [cryptocat/cryptocat#65]
Getting the error message regarding, unable to decrypt message. Ask buddy to send again.

The error message appears constantly at regular intervals regardless whether I or my buddy send a message. Both of us on Linux Mint 64bit.

Same situation on buddy's side as well. Tested it for sending emoticons, words, files.

**Comment by kaepora** [comment]
Are both and your buddy using the latest version (Cryptocat 3.1.01?) I'm guessing one of you is using a version older than 3.0.30. 3.0.29 and lower are not compatible with 3.0.30 and higher.

**Comment by mafster** [comment]
ah yes that worked.

Weird thing though to note. My buddy did click yes to download the latest (when opening the older version he had and that pop up happens asking to d/l newest) and then he ran the new d/l'd one, still had errors.

In any case he went and deleted those d/ls and re downloaded from the website. Works now.
