### ISSUE TITLE
Can't paste credentials in OS X client

### ISSUE THREAD

**Issue by justinmbaker** [cryptocat/cryptocat#67]
I can't paste credentials into either the username or password box of the OS X Cryptocat client. This seems like it's by design, but I've generated a long password with LastPass and typing it to log in would be difficult at best. I've just installed 3.1.02.

**Comment by kaepora** [comment]
Ah yes, I can see why this would happen.

**Comment by kaepora** [comment]
Sorry about this, it was actually only pushed in 3.1.02. Fix will be pushed in 3.1.03.
