### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by ejpcmac** [cryptocat/cryptocat#69]
Hello,

Every single time I try to login on cryptocat I get this error message:

![capture d ecran 2016-04-19 a 01 38 16](https://cloud.githubusercontent.com/assets/6207605/14623103/6e301c42-05cf-11e6-9d69-a6b6d88d9976.png)

I tried on a Windows virtual machine with the same credentials and it works properly. Which is really strange is that it worked when I first tried this new Cryptocat. As far I remember, this bug started to occur after the first update.

I tried to uninstall it and delete the config files before reinstalling it but nothing changes. Please note I’m using the “official” build from https://crypto.cat.

**Comment by kaepora** [comment]
This is literally impossible to debug with the information you've given me. For one thing, I can't reproduce it.
