### ISSUE TITLE
Crypto.cat new cert not inside chrome hsts pins

### ISSUE THREAD

**Issue by Esurnir** [cryptocat/cryptocat#699]
Hello everyone. The app and the website stopped being accessible on chrome since the last round of updates. The reason is crypto.cat is included in the static hsts list chrome has. The certs which must be inside the key chains are https://code.google.com/p/chromium/codesearch#chromium/src/net/http/transport_security_state_static.certs DigiCertEVRoot or CryptoCat1. If you could ask DigiCert to cross-sign the certificate and put it on the server I think it would likely solve the problem until next chrome patch at least.

**Comment by hickford** [comment]
This has been coined 'pinning suicide'

> It's also worth noting that CryptoCat has committed pinning-suicide in Chrome at at the moment due to their CA having switched intermediates between renewals. They're waiting for the release of Chrome 41 to recover.

https://www.imperialviolet.org/2015/01/17/notdane.html
