### ISSUE TITLE
To change the passphrase you should type in the current one first

### ISSUE THREAD

**Issue by ovalseven8** [cryptocat/cryptocat#7]
For more security.

Additionally, I think it makes sense if you have to type in your new passphrase two times to prevent annoying typos.

**Comment by kaepora** [comment]
That's not how the [XEP-0077](http://xmpp.org/extensions/xep-0077.html#usecases-changepw) standard works.

**Comment by ovalseven8** [comment]
@kaepora: Do you know whether it is possible to implement it anyway? I still think that it is not unimportant.
