### ISSUE TITLE
no information on audit from ISECpartners

### ISSUE THREAD

**Issue by hasufell** [cryptocat/cryptocat#701]
I've read both audits from
* https://leastauthority.com/static/publications/LeastAuthority-Cryptocat-audit-report.pdf
* https://isecpartners.github.io/publications/iSEC_Cryptocat_iOS.pdf

For the first one there have been issues opened here and almost all seem to be fixed. For the second one I cannot find anything. Some of the found vulnerabilities seem to overlap with the first audit (I think vulnerability 13 from the second paper might already be fixed?), but it's difficult for the reader to figure out which of those still apply and which not. Especially vulnerability 1, 2, 3 and 13 interest me.

Did you study the second paper from iSECpartners and if so how accurate/up2date is the report now? Or did I just miss something?

It may even make sense to add a wiki page, describing the actions that were taken to address those audits. A lot of people might stumble over them and just think nothing has been done (which is clearly wrong).

**Comment by kaepora** [comment]
https://blog.crypto.cat/?s=isec
