### ISSUE TITLE
nginx "crypto.cat" server uses weak Diffie-Hellman parameters

### ISSUE THREAD

**Issue by selecadm** [cryptocat/cryptocat#702]
When Internet Explorer 11 on Windows 8 users visit crypto.cat, the cipher suite is TLS_DHE_RSA_WITH_AES_128_GCM_SHA256, and the Diffie-Hellman parameters are weaker than RSA (1024 instead of 4096).

Solution below

In terminal:
openssl dhparam -out /path/to/file/dhparam.pem 4096

In nginx configuration ("server" block):
ssl_dhparam /path/to/file/dhparam.pem

**Comment by selecadm** [comment]
I told you and waited for 2 months, now fucking what? Nobody ever listens to me!

https://dev.ssllabs.com/ssltest/analyze.html?d=crypto.cat

![image](https://cloud.githubusercontent.com/assets/10382329/6477978/d6fd83a6-c23a-11e4-9aab-fe376db37bfb.png)

![image](https://cloud.githubusercontent.com/assets/10382329/6478003/40c17afe-c23b-11e4-8e70-8c0060ce73ab.png)

**Comment by kaepora** [comment]
Sorry for the delayed response. I have been extremely busy and unable to check the GitHub issue list. I also think you may believe this issue to be more severe than it actually is.

Either way, the issue has been fixed (feel free to run the SSL Labs test again) and I thank you for your patience.

**Comment by selecadm** [comment]
OK, good! That patience was hard because having RSA 4096 key and DH 1024 parameters makes bad impression of crypto.cat security. Wanted to help until it's too late.
