### ISSUE TITLE
Firefox add-on is not signed, "Author not verified"

### ISSUE THREAD

**Issue by taltman** [cryptocat/cryptocat#703]
When I try to install the crypto.cat Firefox add-on, the confirmation dialog lists the add-on as "(Author not verified)". Seems that this means that the add-on was not cryptographically signed by the author. The add-on should be signed, as the "Author not verified" message may scare away users. Plus, it is good security to be able to both authenticate and verify integrity of the add-on.

**Comment by kaepora** [comment]
This kind of addon signing is not standard for Firefox extensions.

**Comment by taltman** [comment]
I don't understand your comment. Is there a "more standard" way to sign Firefox extensions? Why are you closing the issue?
