### ISSUE TITLE
Build problems

### ISSUE THREAD

**Issue by pettter** [cryptocat/cryptocat#71]
Building on Debian 8.3 does not currently work.

Initially, one needs to make "node" refer to "nodejs" through aliasing, symlinking, or similar measure.

After that, this happens:

npm ERR! peerinvalid The package grunt does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer grunt-electron@3.0.0 wants grunt@>=0.4.0
npm ERR! peerinvalid Peer grunt-exec@0.4.6 wants grunt@~0.4

Whereas cryptocat wants 'latest', which is currently 1.0.0

Doing
-    "grunt": "latest",
+    "grunt": "0.4.0",
in packages.json resolves this.

After this, npm run dev works.

However, npm run linux fails, since grunt is not in the path.

[npm-debug.log.txt](https://github.com/cryptocat/cryptocat/files/228183/npm-debug.log.txt)

**Comment by kaepora** [comment]
This isn't a support forum.
