### ISSUE TITLE
Encrypted Facebook Chat send me to non .onion Facebook URL

### ISSUE THREAD

**Issue by raphaelco** [cryptocat/cryptocat#713]
When I'm in a Tor Browser acessing www.facebookcorewwwi.onion - already logged in - and I want to use cryptocat, clicking in "Chat via Facebook, it sends me to the usual facebook.com in order to confirm that my FB account has the permission to use cryptocat. This would demand that i log in the non .onion FB website thru tor instead of acessing the .onion address.

**Comment by geekman-rohit** [comment]
This totally depends on whether the Facebook API supports  www.facebookcorewwwi.onion, does anyone know about this?

**Comment by raphaelco** [comment]
Well, I'm just an user so I don't know. However, I replaced the www.facebook.com for the .onion address (keeping the things beyond the "/") on the login screen and it worked fine. Hope it helps.
