### ISSUE TITLE
Haven't Been Able to Join Any Rooms

### ISSUE THREAD

**Issue by devomania** [cryptocat/cryptocat#747]
Since last night (12/30) Cryptocat hasn't been able to join any rooms - the progress bar goes all the way to full and then stays there while the pending music plays on a loop. Tried reinstalling with no luck. This happens in both Firefox and Chrome, and though I can't be sure if it's related, I think the issue might have started after a brief ISP outage. 

Any help would be greatly appreciated. Thanks.

**Comment by navyjeff** [comment]
I pulled up the console and saw:
XMLHttpRequest cannot load https://crypto.cat/http-bind. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'chrome-extension://gonbigodpnfghidmnphnadhepmbabhij' is therefore not allowed access. The response had HTTP status code 502.

The problem is with the crypto.cat servers.

**Comment by Steadbrick** [comment]
I wasn't going to post this, but the situation has gone on long enough. I have an alternate server that's up right now -- if you want to connect, enter this info in the "Custom server" field:

Domain: cryptocrap.xyz
XMPP Conference Server: conference.cryptocrap.xyz
BOSH/WebSocket Relay: https://cryptocrap.xyz/http-bind

**Comment by devomania** [comment]
Excellent - thank you, Steadbrick.

**Comment by AjaxBlue** [comment]
https://cryptodog.github.io/cryptodog-webclient/
This should automatically default to the alternate server ayyghost mentioned. I think some users took the initiative to create it due to a lack of response on the developers part. It runs out of the browser no extension necessary.

**Comment by ayyghost** [comment]
Keep in mind, the official Cryptocat extension is still recommended in situations where security is vital. The web client is intended for more casual purposes.

**Comment by devomania** [comment]
Cool, that's good to know. Also, thanks for the link, Ajax.

One last question (sorry if it's a silly one, I'm not super tech savvy). If two people enter a room with the same name via different servers, will they be in the same room? I ask 'cause I'm not sure if the one person I used Crypto to chat with (haven't been able to get in contact with him - Crypto's really the only way we talk, haha) is having the same problems I am or if he's still using the original server.

**Comment by ayyghost** [comment]
> will they be in the same room?

No. Rooms are tied to servers.

**Comment by devomania** [comment]
Well, shoot. I'll have to keep that in mind in the future. In the meantime, it looks like the original server is working again. 

Thanks for your help, guys.
