### ISSUE TITLE
Set urgency window hint on new incoming messages (Linux)

### ISSUE THREAD

**Issue by ledti** [cryptocat/cryptocat#76]
If it's possible to add, this is very useful for users of tiling window managers, and it's generally the preferred method for that use case over libnotify/sound notifications.

**Comment by kaepora** [comment]
How does that work? Any references? I'm new to programming notifications for Linux desktop environments.

**Comment by ledti** [comment]
https://tronche.com/gui/x/icccm/sec-4.html was the best resource I could find. It was linked from a similar issue on another project found [here](https://github.com/foudfou/FireTray/issues/96).

Running the ```xprop``` program from a terminal (and clicking on a window) is a quick way to see what WM_HINTS are applied to a window on Linux.

Another useful utility is ```wmctrl```.

Other related references:
https://specifications.freedesktop.org/wm-spec/wm-spec-latest.html

**Comment by ledti** [comment]
@kaepora 

This is resolved now. New incoming messages set the urgency hint on Linux as of v3.1.25...

If I had to guess, commit https://github.com/cryptocat/cryptocat/commit/3ba86c7d7572b879fb71299e26d3a68321f5a799 is the one that did it.

In any case, you can mark this as resolved, and thanks!

**Comment by kaepora** [comment]
Wow, I'm such a great programmer I fix bugs without even meaning to!
