### ISSUE TITLE
Font sizes on high resolution screens are too small to see comfortably.

### ISSUE THREAD

**Issue by virtadpt** [cryptocat/cryptocat#78]
I've been experimenting with recent builds of Cryptocat for Linux recently and I've noticed a problem with font sizing:

My normal screen resolution is 3200x1800 (a bit larger than Retina) but the fonts are just barely legible; I have to do a fair amount of up-close squinting and sometimes use xorg-mag to blow up the Cryptocat window to see what I'm doing.

Would it be feasible to add the capability of changing the font type and size while Cryptocat is running, and saving the settings for later use?

**Comment by kaepora** [comment]
> Would it be feasible to add the capability of changing the font type and size while Cryptocat is running, and saving the settings for later use?

# I am sorry you are having trouble with font size. Yes, I suppose we could add this capability and document it at some point in time, such as, for example, [the past](https://crypto.cat/help.html#fontSize).
