### ISSUE TITLE
Double "buddy add" request in 3.1.10

### ISSUE THREAD

**Issue by DaniSancas** [cryptocat/cryptocat#84]
First of all, I don't know if I would be able to reproduce this bug, but I tell you how it happened.

Yesterday I was using v3.1.08, and received a "buddy add" request (it was expected). I added that buddy and closed Cryptocat (we had no chat). Today I had the Update notification for the v3.1.10, I downloaded it and executed, everything ok 'till now. Then I logged in and the same "buddy add" request from yesterday appeared. I accepted it again (still no chat with the new buddy, for the record).

Is that a bug? Could be someone trying to do a MITM? (I can ask my buddy analogically to verify the fingerprints, so not big deal). Thanks!

**Comment by kaepora** [comment]
I had this today too. Also happened with a third person (a friend of mine) who privately reported it.

It seems recent. It didn't happen before. Although I don't know what could have made this issue crop up. I'll look into it.

**Comment by kaepora** [comment]
I am no longer able to reproduce this and now believe it was actually due to server maintenance that was occurring around the time the bug happened. Please let me know if it happens again and I will re-open the issue.

**Comment by DaniSancas** [comment]
I've just re-opened the application and happened again!

For the record: I haven't talked to my buddy yet, I believe that hasn't logged in since added me. Version 3.1.10

**Comment by kaepora** [comment]
I just can't reproduce this.

**Comment by DaniSancas** [comment]
I've closed and re-opened the application and this time the bug didn't reproduced. I'll try later to shutdown my computer and re-open the application to see what happens. Maybe this last time was an echo lost in time... :smile_cat:

**Comment by DaniSancas** [comment]
Happened again. I've opened Cryptocat and updated to 3.1.11, then logged in and, surprise! The message appears again.

**Comment by kaepora** [comment]
You were right about this. I figured out the cause: it was a server misconfiguration. This will likely happen again today but will not occur again in the future. My apologies.

**Comment by DaniSancas** [comment]
You're welcome, mate! I'll let you know if it happens again.

**Comment by DaniSancas** [comment]
Logged in again and then the bug did NOT appeared. I think we can definitely close this issue. Thanks!

**Comment by kaepora** [comment]
Great. Thanks.
