### ISSUE TITLE
Destructable Messages on a Timer

### ISSUE THREAD

**Issue by realrasengan** [cryptocat/cryptocat#87]
It would be great to have destructable messages on a timer.  (Such as set 30s means in 30s the message will disappear).

Thank you for everything!!

**Comment by kaepora** [comment]
Sounds good, so long as I figure a way to communicate the security model for those messages clearly in the UI (which is certainly possible.)

**Comment by TumM0reNcE5SsIti** [comment]
I don't know that this is a viable solution.
The recipient can just copy and paste the content, what good does destructible* messages do us, if the message is saved "offline" or if the users screenshots, or copies the message?
If the client somehow blocked those messages from being copied, as they inherently are only supposed to be "seen", I could see this being a viable option, but it just isn't worth coding if the software isn't inherently preventing that message from being copied anyway...the system is encrypted, not blocked from alteration. Let's not create rabbit holes unnecessarily. :)

**Comment by kaepora** [comment]
Yeah, this is a dumb feature.
