### ISSUE TITLE
Client Side Scripting

### ISSUE THREAD

**Issue by realrasengan** [cryptocat/cryptocat#88]
It would be awesome to have client side scripting capabilities so bots and scripts can run locally instead of on a third party "non-trusted" place:
- /commands or aliases
- events
- etc.

Thank you!!

**Comment by kaepora** [comment]
This is very low-priority, and I'll also encourage discussion as it's quite a large feature-set.

**Comment by andersbateva** [comment]
@realrasengan You mean using scripts on your own account, instead of using only on dedicated Bot accounts (like is done on Telegram)?

**Comment by kaepora** [comment]
Nah, screw this.
