### ISSUE TITLE
Is this feature or bug that i have to signup up new user evertime i use  CryptoCat ?

### ISSUE THREAD

**Issue by NCnew** [cryptocat/cryptocat#89]
I and my friends as well face this issue , is this feature or bug. If this is features then i there is issue becasue how will i get offline message send by my friends .

**Comment by kaepora** [comment]
What?! Of course you don't need to sign up for a new user every time! Just log in again with the previous user!

**Comment by NCnew** [comment]
I don't the reason but i and my friend are facing the issue , we cannot login with username and password we sign yesterday and had to create new one today. I will update you trying to find out the cause but i am pretty sure it not because we forget password.

**Comment by kaepora** [comment]
I cannot at all reproduce this.

**Comment by NCnew** [comment]
It is mostly face after 24 hours any i will found out tomorrow and let you know the cause

**Comment by dmh43** [comment]
... I also had this issue actually. I created an account a couple days ago, the next day I tried logging in again but my login credentials were not recognized. I am quite certain I did not forget my username and password.

**Comment by kaepora** [comment]
You were right about this. I figured out the cause: it was a server misconfiguration. This will likely happen again today but will not occur again in the future. My apologies.

**Comment by NCnew** [comment]
It ok , justing want to see crypto cat perfect.
