### ISSUE TITLE
pending buddy requests doesn't work as expected

### ISSUE THREAD

**Issue by pbx0** [cryptocat/cryptocat#9]
I received a buddy request but choose to select "remind me later". Once I did this, it was no longer obvious how to accept the request. I attempted to then finish the request so, I sent a new request by manually typing in the name of that who I received the original request  from. I expected that instead of sending a new request it would finish the half-open one. Instead it just sent a new request.

**Comment by kaepora** [comment]
Simply log out and log back in (quit and relaunch Cryptocat).
