### ISSUE TITLE
2 Clients Open Linux

### ISSUE THREAD

**Issue by TheGoverner** [cryptocat/cryptocat#91]
I  accidentally opened up 2 clients and if I click the first one I opened, it only shows an empty window and it wont allow me to quit from the task bar (it does show the menu but it does nothing) 
I am running Arch Linux currently, Cryptocat ver. 3.1.11

**Comment by kaepora** [comment]
Cannot reproduce. I open two clients regularly for testing.

**Comment by TheGoverner** [comment]
my  bad I'm slow today, it was random
