### ISSUE TITLE
Remember login

### ISSUE THREAD

**Issue by bungabunga** [cryptocat/cryptocat#93]
I know Cryptocat is a privacy oriented chat application but is there really a need to log in with a password every time you boot the computer?

We'd like to use Cryptocat in a small organisation where every computer have different users every day and Cryptocat usernames would not be computer users but computers (Comp1, Comp2, Comp3...). It's a voluntary type of organisation so there's no way to enforce users to log in with usernames and passwords every time they boot their computers but having Cryptocat always on and working would really help our communication. We love Cryptocat's privacy but having Cryptocat accounts unlocked on computers all the time is not a security risk for us, it only matters that the outside communication is encrypted.

Would you consider to implement this feature? Of course the passwordless log in would be off by default but I imagine we are not the only ones with  not so tight threat model and the need for this feature.

**Comment by kaepora** [comment]
This is really funny. I actually just sat down in a coffee shop in order to implement exactly this feature.

**Comment by bungabunga** [comment]
wow! :D

**Comment by kaepora** [comment]
@bungabunga [Update 3.1.13 is now available](https://crypto.cat/news.html#3.1.13) and introduces this feature.

**Comment by bungabunga** [comment]
That's cool, man! Thank you! I'm really impressed how you made so great and also beautiful app in such a short time.
