### ISSUE TITLE
Strange visual artifacts when downloading new version through Cryptocat app

### ISSUE THREAD

**Issue by bungabunga** [cryptocat/cryptocat#96]
Since 3.1.12 every time I download a  new version through Cryptocat app I see some strange visual artifacts on downloader window. I can't say if the bug is gone in the latest version since there is nothing to download yet.

Ubuntu 16.04
![crptcc](https://cloud.githubusercontent.com/assets/2994878/14952114/e13400bc-105d-11e6-9411-7505314b3a81.png)

**Comment by kaepora** [comment]
This is fixed in 3.1.14. It's a very silly bug, I left debug mode on in the update downloader code.
